Repository ftrevo/tentacle-android, pull requests merged in 2019-03, with the labels that each got.

#308 Adapting home tests
  app/build.gradle
  app/src/androidTest/java/br/com/concrete/tentacle/features/home/HomeFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/matchers/RecyclerViewMatcher.kt
  app/src/debug/assets/mockjson/home/new_home_games_success.json
  app/src/test/java/br/com/concrete/tentacle/features/home/HomeVMTest.kt
  build.gradle
Labels: In Review

#307 81 test unit pagination
  app/src/main/java/br/com/concrete/tentacle/data/models/MediaResponse.kt
  app/src/test/java/br/com/concrete/tentacle/features/home/HomeVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/library/LibraryVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchViewModelTest.kt
Labels: In Review

#324 07 test unit reservas detalhe
  app/src/debug/assets/mockjson/myreservations/myreservations_detail_success.json
  app/src/test/java/br/com/concrete/tentacle/features/myreservations/MyReservationDetailVMTest.kt
Labels: In Review

#337 35_TEST_unit_cadastro_jogo_externo
  app/src/debug/assets/mockjson/registerMedia/detail_game_success.json
  app/src/main/java/br/com/concrete/tentacle/custom/GameView.kt
  app/src/test/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaViewModelTest.kt
Labels: In Review

#405 Updating Home Instrumented Test
  app/src/androidTest/java/br/com/concrete/tentacle/features/home/HomeFragmentTest.kt
  app/src/debug/assets/mockjson/home/new_home_games_success.json
  app/src/main/java/br/com/concrete/tentacle/data/models/Game.kt
Labels: Reviewed

#407 Implementação teste instrumentados
  app/src/androidTest/java/br/com/concrete/tentacle/features/library/LibraryFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesFragmentTest.kt
  app/src/debug/assets/mockjson/library/get_library_success.json
  app/src/debug/assets/mockjson/library/get_library_success_second.json
  app/src/debug/assets/mockjson/loadmygames/load_my_games_remove_success.json
  app/src/debug/assets/mockjson/loadmygames/load_my_games_success.json
  app/src/debug/assets/mockjson/loadmygames/load_my_games_success_second.json
Labels: Reviewed

#413 264 task add detail game
  app/src/main/java/br/com/concrete/tentacle/di/ViewModelModule.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/loan/LoanActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/loan/LoanViewModel.kt
  app/src/main/res/layout/activity_loan.xml
Labels: Reviewed

#415 377 task comfirm password recovery
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/concrete/tentacle/custom/BaseTentacleLabeledWidget.kt
  app/src/main/java/br/com/concrete/tentacle/custom/TentacleEditText.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/PasswordRecovery.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiServiceAuthentication.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/UserRepository.kt
  app/src/main/java/br/com/concrete/tentacle/di/ViewModelModule.kt
  app/src/main/java/br/com/concrete/tentacle/extensions/ActivityExt.kt
  app/src/main/java/br/com/concrete/tentacle/extensions/ActivityExtension.kt
  app/src/main/java/br/com/concrete/tentacle/extensions/StringExt.kt
  app/src/main/java/br/com/concrete/tentacle/features/forgotPassword/passwordRecovery/PasswordRecoveryActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/forgotPassword/passwordRecovery/PasswordRecoveryFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/forgotPassword/passwordRecovery/PasswordRecoveryViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/forgotPassword/sendEmail/ForgotPassSendEmailActivity.kt
  app/src/main/res/layout/activity_password_recovery.xml
  app/src/main/res/layout/fragment_password_recovery.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/br/com/concrete/tentacle/features/forgotPassword/sendEmail/ForgotPassSendEmailVMTeste.kt
Labels: Reviewed

#414 264 task add carrossel
  app/build.gradle
  app/src/androidTest/java/br/com/concrete/tentacle/features/gameViewComponent/GameViewTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/registerGame/remoteGame/RemoteGameFragmentTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/concrete/tentacle/data/models/game/Screenshot.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/Library.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/Video.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/loan/LoanActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/loan/LoanActivitySuccess.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/loan/LoanViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/loan/PinchToZoomActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaFragment.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
  app/src/main/java/br/com/concrete/tentacle/utils/DialogUtils.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Utils.kt
  app/src/main/res/drawable/ic_play.xml
  app/src/main/res/drawable/player.xml
  app/src/main/res/layout/activity_loan.xml
  app/src/main/res/layout/activity_pinch_to_zoom.xml
  app/src/main/res/layout/item_game_video.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: In Review

#416 260_TASK_Sistema_Emprestimo_Tela
  app/src/main/java/br/com/concrete/tentacle/custom/StateButtonView.kt
  app/src/main/java/br/com/concrete/tentacle/custom/StateButtonWhiteView.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/ActiveLoan.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/Media.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/RememberDeliveryResponse.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/loan/LoanResponse.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiService.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/GameRepository.kt
  app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameActivitySuccess.kt
  app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
  app/src/main/res/drawable/shape_border_rounded_red.xml
  app/src/main/res/layout/activity_lend_game.xml
  app/src/main/res/layout/activity_loan.xml
  app/src/main/res/layout/activity_my_reservations_details.xml
  app/src/main/res/layout/button_custom.xml
  app/src/main/res/layout/dashed_include.xml
  app/src/main/res/layout/fragment_register_media.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Fixed

#460 Testes instrumentados
  app/src/androidTest/java/br/com/concrete/tentacle/myreservations/MyReservationFragmentTest.kt
Labels: In Review

#470 task 257
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/concrete/tentacle/base/BaseActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/menu/MenuFragment.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/shape_camera_profile.xml
  app/src/main/res/layout/activity_host.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
Labels: Reviewed

#474 Bug sistema emprestimo
  app/src/main/java/br/com/concrete/tentacle/data/models/ActiveLoan.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiService.kt
  app/src/main/java/br/com/concrete/tentacle/extensions/StringExt.kt
  app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameActivitySuccess.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
Labels: Reviewed

#467 385 task perfil layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/concrete/tentacle/custom/ListError.kt
  app/src/main/java/br/com/concrete/tentacle/custom/TentacleEditText.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/UserRequest.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiService.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/UserLoggedRepository.kt
  app/src/main/java/br/com/concrete/tentacle/di/RepositoryModule.kt
  app/src/main/java/br/com/concrete/tentacle/di/ViewModelModule.kt
  app/src/main/java/br/com/concrete/tentacle/features/profile/ProfileActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/profile/ProfileFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/profile/ProfileViewModel.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/progress_include.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Reviewed

#482 257 task load user data
  app/src/main/java/br/com/concrete/tentacle/data/repositories/SharedPrefRepository.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/UserRepository.kt
  app/src/main/java/br/com/concrete/tentacle/di/RepositoryModule.kt
  app/src/main/java/br/com/concrete/tentacle/di/ViewModelModule.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/login/LoginViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/menu/MenuFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/menu/MenuViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/register/RegisterUserViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/navigation/nav_host.xml
  app/src/main/res/values/strings.xml
Labels: Reviewed

#483 257 Task Instrumented Test
  app/src/androidTest/java/br/com/concrete/tentacle/features/menu/MenuFragmentTest.kt
  app/src/debug/assets/mockjson/profile/get_profile_success_another_user.json
  app/src/main/java/br/com/concrete/tentacle/data/repositories/SharedPrefRepository.kt
  app/src/main/java/br/com/concrete/tentacle/features/menu/MenuFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/menu/MenuViewModel.kt
Labels: Reviewed

#527 File adjustments
  app/src/androidTest/java/br/com/concrete/tentacle/features/filter/FilterDialogFragmentTest.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/FilterRepository.kt
  app/src/main/java/br/com/concrete/tentacle/di/ViewModelModule.kt
  app/src/main/java/br/com/concrete/tentacle/features/filter/FilterDialogFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/filter/FilterViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryFragment.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
Labels: Reviewed

#537 [Meus Jogos > Jogos Inativos - #499] - Criar filtro e tratar paginação
  app/src/main/assets/dummy_filter_itens_library.json
  app/src/main/assets/dummy_fiter_itens_my_games.json
  app/src/main/java/br/com/concrete/tentacle/data/models/QueryParameters.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/filter/FilterItem.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/filter/SubItem.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiService.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/FilterRepository.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/GameRepository.kt
  app/src/main/java/br/com/concrete/tentacle/features/filter/FilterDialogFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/filter/FilterViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
  app/src/main/java/br/com/concrete/tentacle/utils/QueryUtils.kt
  app/src/main/res/menu/menu_load_my_games.xml
  app/src/test/java/br/com/concrete/tentacle/features/library/LibraryVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/myreservations/MyReservationVMTest.kt
Labels: In Review
