Repository ftrevo/tentacle-android, pull requests merged in 2019-02, with the labels that each got.

#120 Aumentar o espaço (padding) entre os campos de estado e cidade
  app/src/main/res/layout/register_fragment.xml
Labels: Approved

#117 94 register platform unit tests
  app/src/main/assets/mockjson/registerMedia/game.json
  app/src/main/assets/mockjson/registerMedia/register_media_success.json
  app/src/main/java/br/com/concrete/tentacle/base/BaseSearchFragment.kt
  app/src/test/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaViewModelTest.kt
Labels: Approved

#118 25 task test
  app/build.gradle
  app/com.crashlytics.settings.json
  app/src/androidTest/java/br/com/concrete/tentacle/TentacleTestApp.kt
  app/src/androidTest/java/br/com/concrete/tentacle/base/BaseFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/HostActivityTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/home/HomeFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesFragmentTest.kt
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/br/com/concrete/tentacle/testing/BottomBarTestActivity.kt
  app/src/debug/res/layout/activity_bottom_bar_test.xml
  app/src/main/assets/mockjson/home/load_home_games_success.json
  app/src/main/assets/mockjson/home/load_home_games_success_empty.json
  app/src/main/assets/mockjson/loadmygames/load_my_games_empty_list_success.json
  app/src/main/java/br/com/concrete/tentacle/base/AppTentacle.kt
  app/src/main/java/br/com/concrete/tentacle/base/BaseSearchFragment.kt
  app/src/main/java/br/com/concrete/tentacle/custom/ListCustom.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/GameResponse.kt
  app/src/main/java/br/com/concrete/tentacle/di/NetworkModule.kt
  app/src/main/java/br/com/concrete/tentacle/di/RepositoryModule.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameFragment.kt
  app/src/main/res/layout/item_game.xml
  app/src/main/res/layout/list_error_custom.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/br/com/concrete/tentacle/base/BaseViewModelTest.kt
  app/src/test/java/br/com/concrete/tentacle/data/repositories/SharedPrefRepositoryTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/home/HomeVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/login/LoginVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/register/RegisterUserVMTest.kt
Labels: Reviewed

#116 06_TASK_Biblioteca_ViewModel
  app/src/main/java/br/com/concrete/tentacle/data/models/library/Library.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/LibraryResponse.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/MediaLibrary.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/LibraryRepository.kt
  app/src/main/java/br/com/concrete/tentacle/di/RepositoryModule.kt
  app/src/main/java/br/com/concrete/tentacle/di/ViewModelModule.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryViewModel.kt
  app/src/main/res/layout/fragment_library.xml
  app/src/main/res/navigation/nav_host.xml
  app/src/main/res/values/strings.xml
Labels: Approved

#135 13_refactoring_state_event
  app/src/androidTest/java/br/com/concrete/tentacle/base/BaseFragmentNoActionBarNoBottomBarTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/base/BaseFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/base/BaseInstrumentedTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/extensions/StringExtensions.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/register/RegisterFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaFragmentTest.kt
  app/src/debug/java/br/com/concrete/tentacle/testing/SingleFragmentTestActivityNoActionBarNoBottomBar.kt
  app/src/main/java/br/com/concrete/tentacle/features/login/LoginFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/login/LoginViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/register/RegisterFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/register/RegisterUserViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Event.kt
  app/src/test/java/br/com/concrete/tentacle/features/login/LoginVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/register/RegisterUserVMTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaViewModelTest.kt
Labels: Reviewed

#138 2 task instrumented test
  app/src/androidTest/java/br/com/concrete/tentacle/base/BaseFragmentNoActionBarNoBottomBarTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/login/LoginFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/register/RegisterFragmentTest.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiService.kt
  app/src/main/java/br/com/concrete/tentacle/extensions/ViewExt.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/login/LoginViewModel.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameViewModel.kt
  app/src/main/res/layout/item_home_game.xml
  app/src/test/java/br/com/concrete/tentacle/features/library/LibraryVMTest.kt
Labels: Reviewed

#137 06 us biblioteca
  app/src/androidTest/java/br/com/concrete/tentacle/base/BaseFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/base/ScreenshotTestRule.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/library/LibraryFragmentTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesFragmentTest.kt
  app/src/debug/AndroidManifest.xml
  app/src/debug/assets/mockjson/common/common_empty_list_success.json
  app/src/main/java/br/com/concrete/tentacle/base/BaseFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryViewHolder.kt
  app/src/main/res/layout/library_item_layout.xml
  app/src/main/res/values/strings.xml
Labels: Reviewed

#178 03 task logout impl
  app/src/androidTest/java/br/com/concrete/tentacle/features/HostActivityLogoutTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/HostActivityTest.kt
  app/src/main/java/br/com/concrete/tentacle/data/repositories/SharedPrefRepository.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/utils/DialogUtils.kt
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/br/com/concrete/tentacle/features/home/LogoutTest.kt
Labels: Reviewed

#206 152_bug_ancora_float_action_button
  app/src/main/java/br/com/concrete/tentacle/data/models/Game.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameViewHolder.kt
Labels: Reviewed

#207 60 task realizar emprestimo tela
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/concrete/tentacle/base/BaseActivity.kt
  app/src/main/java/br/com/concrete/tentacle/custom/ButtonView.kt
  app/src/main/java/br/com/concrete/tentacle/custom/ChipCustom.kt
  app/src/main/java/br/com/concrete/tentacle/custom/StateButtomView.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/Library.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/library/MediaLibrary.kt
  app/src/main/java/br/com/concrete/tentacle/extensions/ActivityExtension.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LibraryViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/library/LoanActivity.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Utils.kt
  app/src/main/res/anim/translate_fade_in.xml
  app/src/main/res/anim/translate_fade_out.xml
  app/src/main/res/anim/translate_left_enter.xml
  app/src/main/res/anim/translate_left_exit.xml
  app/src/main/res/anim/translate_no_change.xml
  app/src/main/res/anim/translate_right_enter.xml
  app/src/main/res/anim/translate_right_exit.xml
  app/src/main/res/anim/translate_slide_down.xml
  app/src/main/res/anim/translate_slide_up.xml
  app/src/main/res/color/color_chip_state.xml
  app/src/main/res/drawable/bg_chip_default.xml
  app/src/main/res/drawable/bg_chip_selected.xml
  app/src/main/res/drawable/bg_chip_selector.xml
  app/src/main/res/drawable/shape_border_corners_3dp.xml
  app/src/main/res/drawable/shape_border_rounded_diasabled.xml
  app/src/main/res/layout/activity_loan.xml
  app/src/main/res/layout/fragment_loan.xml
  app/src/main/res/navigation/nav_host.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/typography.xml
  build.gradle
Labels: Fixed

#219 60_TASK_Realizar_Emprestimo_TesteUnitario
  app/src/debug/assets/mockjson/library/get_one_library_success.json
  app/src/test/java/br/com/concrete/tentacle/features/library/loan/LoanVMTest.kt
Labels: Reviewed

#220 164 test unit filter
  app/src/androidTest/java/br/com/concrete/tentacle/features/library/filter/FilterDialogFragmentTest.kt
  app/src/debug/assets/mockjson/library/get_library_after_filter_success.json
  app/src/debug/assets/mockjson/library/get_library_error.json
  app/src/main/java/br/com/concrete/tentacle/data/models/Game.kt
  app/src/test/java/br/com/concrete/tentacle/features/library/LibraryVMTest.kt
Labels: Reviewed

#217 60_TASK_Realizar_Emprestimo_TesteInstrumentado
  app/src/androidTest/java/br/com/concrete/tentacle/features/library/loan/LoanActivityTest.kt
  app/src/androidTest/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaFragmentTest.kt
  app/src/debug/assets/mockjson/library/loan/library_response_success.json
Labels: Fixed

#297 Load home image :: assemble image url
  app/src/main/java/br/com/concrete/tentacle/extensions/ImageExt.kt
  app/src/main/java/br/com/concrete/tentacle/features/login/LoginFragment.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Constants.kt
  app/src/main/java/br/com/concrete/tentacle/utils/Utils.kt
Labels: In Review

#301 Home item layout adjustments
  app/src/main/java/br/com/concrete/tentacle/data/models/Game.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/game/Screenshot.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeViewHolder.kt
  app/src/main/res/drawable/bg_gradient.xml
  app/src/main/res/layout/game_view_header_layout.xml
  app/src/main/res/layout/item_home_game.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: In Review
