Repository ftrevo/tentacle-android, pull requests merged in 2019-01, with the labels that each got.

#112 25 home frontend
  app/session_analytics.tap
  app/session_analytics_to_send/sa_e3ac28d0-3f18-4dc0-b249-7d50be32d0ec_1548264751389.tap
  app/src/main/java/br/com/concrete/tentacle/base/BaseSearchFragment.kt
  app/src/main/java/br/com/concrete/tentacle/custom/BottomBar.kt
  app/src/main/java/br/com/concrete/tentacle/data/interfaces/CallBack.kt
  app/src/main/java/br/com/concrete/tentacle/features/HostActivity.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/home/HomeViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesViewHolder.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameViewHolder.kt
  app/src/main/res/drawable-hdpi/arrow_back.png
  app/src/main/res/drawable-hdpi/icn_search.png
  app/src/main/res/drawable-hdpi/img_background_home.png
  app/src/main/res/drawable-mdpi/arrow_back.png
  app/src/main/res/drawable-mdpi/img_background_home.png
  app/src/main/res/drawable-xhdpi/arrow_back.png
  app/src/main/res/drawable-xhdpi/img_background_home.png
  app/src/main/res/drawable-xxhdpi/arrow_back.png
  app/src/main/res/drawable-xxhdpi/img_background_home.png
  app/src/main/res/drawable-xxxhdpi/arrow_back.png
  app/src/main/res/drawable-xxxhdpi/img_background_home.png
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/button_custom.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_game.xml
  app/src/main/res/layout/item_game_search.xml
  app/src/main/res/layout/item_home_game.xml
  app/src/main/res/layout/list_custom.xml
  app/src/main/res/layout/list_error_custom.xml
  app/src/main/res/menu/menu_search.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/typography.xml
Labels: Reviewed

#109 Instrumented test to BottomBar Navigation
  app/src/androidTest/java/br/com/concrete/tentacle/features/HostActivityTest.kt
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/br/com/concrete/tentacle/testing/BottomBarTestActivity.kt
  app/src/debug/res/layout/activity_bottom_bar_test.xml
Labels: Reviewed

#114 5 task search game test
  app/com.crashlytics.settings.json
  app/src/main/assets/mockjson/searchgame/list_game_empty_success.json
  app/src/main/assets/mockjson/searchgame/list_game_success.json
  app/src/main/assets/mockjson/searchgame/register_game_success.json
  app/src/test/java/br/com/concrete/tentacle/base/BaseViewModelTest.kt
  app/src/test/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchViewModelTest.kt
Labels: In Review

#106 register platform ui tests
  app/com.crashlytics.settings.json
  app/src/androidTest/java/br/com/concrete/tentacle/features/registerMedia/RegisterMediaFragmentTest.kt
  app/src/debug/AndroidManifest.xml
  app/src/debug/assets/mockjson/loadmygames/register_media_success.json
  app/src/debug/java/br/com/concrete/tentacle/testing/OpenForTesting.kt
  app/src/main/assets/mockjson/loadmygames/game_register_media_success.json
  app/src/main/assets/mockjson/loadmygames/register_media_success.json
  app/src/main/java/br/com/concrete/tentacle/base/BaseFragment.kt
  app/src/main/java/br/com/concrete/tentacle/data/models/RegisteredMediaResponse.kt
  app/src/main/java/br/com/concrete/tentacle/data/network/ApiService.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaFragment.kt
  app/src/main/java/br/com/concrete/tentacle/features/registerGame/registerMedia/RegisterMediaViewModel.kt
  app/src/main/res/layout/fragment_register_media.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/br/com/concrete/tentacle/base/BaseViewModelTest.kt
Labels: Fixed
